### ISSUE TITLE
Can not multiplex a pod containers process streams (stdin, stdout, stderr) with hyperstart

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#85]
When creating a new container process through hyperstart, we currenly pass it random `stdio` and `stderr` sequence numbers. Those sequence numbers are used to multiplex containers streams through the single hyperstart IO serial interface, but we do not use them currently. We simply lose all streams from all containers.

In order to e.g. demux all stdout streams from all running containers we should be able to keep a mapping of those sequence numbers to container IDs, and then forward each stream to a given file descriptor passed to us.

We basically have 2 solutions for this:

1) Handle the multiplexing/demultiplexing of stin/stdout and the forwarding part from `virtcontainers`

Or

2) Rely on an external component and have `virtcontainers` rely on it for handling all containers process streams.

Solution 1 seems to be outside of `virtcontainers` scope, solution 2 looks better.

## TODO ##

1) [ ] Handle the container `Console` field as a boolean and set hyperstart `Process` structure accordingly
2) [ ] Create a `Proxy` interface for connecting, disconnecting, attaching and possibly sending raw commands to it. It will be up to a `Proxy` implementation to interpret the raw commands and understand if they need to be encapsulated or not. In other words, the `virtcontainers` hyperstart agent implementation will send the same data to either a `Proxy` implementation or hyperstart itself.
3) [ ] Implement a `cc-proxy` support.

**Comment by sameo** [comment]
cc @dlespiau

**Comment by dlespiau** [comment]
I think we'd like https://github.com/01org/cc-oci-runtime/issues/342 for that one. The client code would only have to know about 2 fds (ctl & io) and the hyperstart protocol. That way, having a proxy or not will be effectively transparent (except the initialisation). As @sameo would say, a real proxy instead of encapsulation for the ctl commands.

**Comment by sameo** [comment]
@dlespiau Yes. I was about to open a cc-oci-runtime issue for that, glad to see there's one already ;)
We can start working on this issue from `virtcontainers` and keep the whole encapsulation in our cc-proxy layer and change it when #342 is done.

**Comment by sameo** [comment]
@dlespiau Also, on the sequence number allocations, we can decide to let the client generate it and let it know if it conflicts with an already existing allocation. This would simplify the protocol itself.

**Comment by dlespiau** [comment]
we could indeed do that, one would have to be terribly unlucky to collide on the 64 bits seq number with only a few processes per VM. Just need to make sure we receive an error from hyperstart.

**Comment by sboeuf** [comment]
cc-proxy supports is already implemented and ready ! Let's close this one!
